[build]
  base = "./"
  command = "npm run build"
  publish = "dist"
  functions = "functions" # This seems to help local Netlify detect functions
[dev]
  base = "./"
  command = "npm run dev"
  publish = "dist"
  functions = "functions" # This seems to help local Netlify detect functions